### ISSUE TITLE
将坐标点添加至共享没有反应

### ISSUE THREAD

**Issue by EEpier** [LazyAlienServer/Where2go#11]
<img width="254" alt="909fe5d69b61482c2875ecc5778b03dc" src="https://github.com/user-attachments/assets/7f61174f-a3b7-4131-9b5b-40d32577ab8f">
点击 [+] 没有反应, 坐标也没有被添加进列表

**Comment by EEpier** [comment]
插件版本v0.2.3

**Comment by tanhHeng** [comment]
客户端版本是否`>1.19`且添加了`LetMeClickAndSend`模组
