### ISSUE TITLE
使用插件时报错

### ISSUE THREAD

**Issue by HanYuCR** [LazyAlienServer/Where2go#12]
![image](https://github.com/user-attachments/assets/56de8c6b-3bd9-42e1-b3cf-f95cbfd08917)
玩家使用!!here时控制台输出
![image](https://github.com/user-attachments/assets/3ea102e6-13c1-4483-b571-a28a0158ff7d)
!!vris输出

**Comment by HanYuCR** [comment]
插件版本0.2.5

**Comment by tanhHeng** [comment]
服务端修改了list指令的输出？如果是单行输出的话调整配置文件中的正则表达式，如果是多行输出的话暂不支持

**Comment by tanhHeng** [comment]
可能会在更新版本中加入忽略list检查（

**Comment by HanYuCR** [comment]
huh?
如果是修改了list输出导致问题，那么我想我知道问题出在哪了
100%是essentialsx搞得鬼，这玩意最喜欢改原版命令

**Comment by HanYuCR** [comment]
是的，的确是ess的问题，修改之后就能正常使用了，感谢

**Comment by tanhHeng** [comment]
okk
