### ISSUE TITLE
难绷

### ISSUE THREAD

**Issue by HanYuCR** [LazyAlienServer/Where2go#13]
你知道我要说什么的（
![image](https://github.com/user-attachments/assets/719afd93-5477-4617-9b15-35877b0622e8)

**Comment by tanhHeng** [comment]
呃草了
还是改正则试试

**Comment by HanYuCR** [comment]
ok解决了
因为我这个核心输指令返回的是中文，所以正则匹配不上，改成中文就OK了 (
![image](https://github.com/user-attachments/assets/9d265968-c26a-481b-a146-b0e2628e1c66)
