### ISSUE TITLE
使用插件时报错

### ISSUE THREAD

**Issue by zhenzhen0915** [LazyAlienServer/Where2go#14]
MCDR版本：2.13.1
Where2go版本：0.2.5
<img width="316" alt="屏幕截图 2024-10-18 235006" src="https://github.com/user-attachments/assets/1ad4eed8-58d7-4db1-adf6-d70a6efd3d2f">
<img width="747" alt="屏幕截图 2024-10-18 235142" src="https://github.com/user-attachments/assets/5bd81fe0-0103-4532-a7ee-76f72c688838">
<img width="751" alt="屏幕截图 2024-10-18 235213" src="https://github.com/user-attachments/assets/7d5d3830-9560-4459-a6af-ded312991e5a">

谢谢！

**Comment by tanhHeng** [comment]
你这报错报的不是我的插件啊（
直接在插件目录里面把原来的WhereIs插件删了就行
