### ISSUE TITLE
查询不了玩家位置

### ISSUE THREAD

**Issue by Redapple-one** [LazyAlienServer/Where2go#9]
![image](https://github.com/user-attachments/assets/4dc8c0f5-6053-46c0-a83f-ba0f8b6cdd97)
![image](https://github.com/user-attachments/assets/2a5dd007-99b3-41a5-add1-9d887f58ce29)

**Comment by tanhHeng** [comment]
请提供控制台报错信息和配置文件

**Comment by tanhHeng** [comment]
尝试使用`v0.2.3`版本插件并检查是否仍然存在问题

**Comment by Redapple-one** [comment]
OK

**Comment by Redapple-one** [comment]
问题已解决
